### ISSUE TITLE
stddef.h file not found (Arch Linux)

### ISSUE THREAD

**Issue by 0----0** [zdevito/terra#120] opened 2015-09-16 22:48 UTC
Same problem as #92.  Only affects the official binary release - doesn't happen if built from source.  The binary release doesn't seem to actually have an include/clang_resource directory, so I was unable to check for the file there.  It affected a friend of mine running the same OS.  Arch Linux x86_64.

**Comment by zdevito** [comment] 2015-09-17 22:17
I've changed it so that things like stddef.h are stored internally in libterra.a
It is possible that the script that does this didn't work correctly. If you look in build/internalizedfiles.h, you should see an array headerfile_names of the files it has included, which should have stddef.h. If it doesn't try building again, and let me know what the file looks likes.

**Comment by 0----0** [comment] 2015-09-19 22:11
When I build 84bbb0b from source, it works fine.  The name is present in build/internalizedfiles.h.  It's the binary release 84bbb0b, acquired from https://github.com/zdevito/terra/releases, that has the error.

**Comment by zdevito** [comment] 2015-09-21 18:18
Hmm, the binary version can include stddef.h on my Ubuntu 14.04 box, so this appears to be an issue using the binaries built for that box on a different Linux distro. For now, I'd recommend just using the one built from source on that platform.

**Comment by HalosGhost** [comment] 2016-01-05 15:07
@zdevito, unfortunately, that can cause a lot of problems. Arch is rolling-release, so most everything official is kept at the latest version; for example, clang is at version 3.7 in the repos.

There is clang35 which offers clang 3.5 in the repos, but it conflicts with the most current version of clang (unsurprisingly), so we cannot have both installed.

**Comment by gabriel-fallen** [comment] 2016-01-16 20:44
I have the same issue with the binary build 84bbb0b downloaded from releases page on Ubuntu 15.10 x86-64.
System stddef.h is in /usr/include/linux
terra executable don't see it.

**Comment by zdevito** [comment] 2016-01-16 20:58
I think this was fixed by #141 but I haven't had time to rebuilt the binaries since then. If this still occurs after rebuilding from the latest check-in, let me know.

**Comment by gabriel-fallen** [comment] 2016-01-17 18:16
After building from sources it works fine. Thanks.

**Comment by elliottslaughter** [comment] 2018-12-03 21:59
Sounds like this is fixed if building from source, but if not please feel free to comment (ideally after having reproduced on master).

**Closed by elliottslaughter** 2018-12-03 21:59 UTC
