### ISSUE TITLE
Build environment/c compiler dependency

### ISSUE THREAD

**Issue by ghost** [zdevito/terra#240] opened 2017-05-30 17:54 UTC
So I have noticed that terra build system is made fragile in how it interacts with LLVM. I have seen this in other projects that rely heavily on LLVM internals too. This is only a problem if one does not have the option of duplicating the precise build environment that it expects. So my question is: What build environment were the latest release binaries built in? What build environments are developers using that leads to all of the tests in master passing? linux distribution, packages, environment variables, command line options, etc.

I have had some success on building master on nixos, but I have yet to get any of my builds to pass a large minority of the tests in master. Various issues with JIT and locating binaries and headers at runtime (partly to do with nixOS being made almost entirely out of symlinks).

My goal in asking this is to be able to compile master and have all of the tests in it pass  (and have all of the cuda tests actually run). Then from there, if I can manage it, help to get the build system into a state where one can follow some simple instructions and do the same in more places.

I would also like to try and generalize the c compiler dependency on windows, because getting a copy of vs2013 c++ build tools requires downloading several gigabytes of other visual studio crap. So if, for instance, you wanted to distribute your source code and run/compile it on the user's machine against the terra compiler, the user would have to sit through an installation of Visual Studio, and then they would have Visual Studio installed for no good reason. 

I have not been able to find a public download link for the compiler independent of the IDE. If you guys have, please let me know where.

It would also be cool if it could be made to use intel, mingw or lcc compilers, or some other easy to acquire/repackage/relicense c compiler for windows.

**Comment by elliottslaughter** [comment] 2018-06-14 05:01
This is at least partially mitigated now by the addition of Travis/AppVeyor tests. In theory, it should be possible to read the CI tests scripts and exactly reproduce the environment where the tests are running. (E.g. Travis is running on Ubuntu 14.04 with packages `clang-3.8 libclang-3.8-dev llvm-3.8-dev` or the equivalent for 3.5.)

If you or anyone else here still has interest, there's still more to be done to make the build less fragile. For example, on Ubuntu 16.04, something about how the LLVM packages are built is throwing the build system off. (Which means Ubuntu 16.04 users end up building from source.)

**Comment by elliottslaughter** [comment] 2018-12-03 19:49
This situation is much better now since we test a variety of Visual Studio versions in AppVeyor. I will also make sure the compiler versions get documented in the next release.

FYI, we're setting up for the next release here, and there are binaries that might be more likely to work now: #323

Another thing to note is that we've merged CMake support. There are cases where I just can't get the old Makefile to build, but CMake works.

I'm closing this for now but please let us know if you hit any other issues.

**Closed by elliottslaughter** 2018-12-03 19:49 UTC
