### ISSUE TITLE
Trying to use libSDL2 using terralib.linklibrary causes SIGSEGV

### ISSUE THREAD

**Issue by max1220** [zdevito/terra#304] opened 2018-09-09 10:50 UTC
I'm trying to use the SDL2 C library from a terra file on Debian Stable(terra from git):
`terralib.linklibrary("/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0")`
`local sdl = terralib.includec("SDL2/SDL.h")`
`sdl.SDL_Init(sdl.SDL_INIT_VIDEO)`

But this causes a SIGSEGV(SEGV_ACCERR) if run in the REPL.
If I export the function in a wrapper using
`terralib.saveobj("terra-sdl_test", "executable", { main = main }, { "-lSDL2" })`
and execute the file from the shell, it works fine.

I can confirm that I used the correct headers, because I implemented a C version of this test.
I'm also certain that I link the correct library using linklibrary because `ldd ./terra-sdl_test` shows the same .so file, and works fine. Other dynamically loaded librarys work fine(e.g. ncurses loaded via linklibrary works)

On the gist are 4 files, `sdl_test.t`(A test that shows the problem), `sdl_test.c`(The C Implementation, for comparison), and 2 strace logs, running with and without swap.
https://gist.github.com/max1220/3d9d89c31831f2cd4e95bab9bde73089

Any help would be appreciated! :P

**Comment by elliottslaughter** [comment] 2018-09-10 20:28
I don't have time to test this at the moment, but it seems to me the next thing to try would be to write a pure LuaJIT program using LuaJIT's FFI that does the same. Terra's FFI functionality is mostly implemented on top of LuaJIT FFI (except that Terra uses Clang so that you can parse real C header files), so in theory it should be possible to write a reproducer in pure LuaJIT. If so, then you can take that to the LuaJIT maintainers, and if not, then that'll hopefully help us discover what's different about Terra's FFI.

**Comment by max1220** [comment] 2018-09-11 07:50
I found this library, which is basically a LuaJIT FFI binding to SDL2: https://github.com/torch/sdl2-ffi.
When using this to implement the test, everything works as expected.
sdl2-ffi does ship it's own cdefs, but terra should be using clang to parse the headers, right?

**Comment by elliottslaughter** [comment] 2018-09-11 17:39
For what it's worth, your programs in this issue and your gist work fine for me on Ubuntu 16.04 and LLVM 6.0.

Can you give me more complete reproduction instructions? E.g. is `debian:stable` the right Docker image to use? What LLVM version are you on and how did you install it?

**Comment by PyryM** [comment] 2018-09-20 23:00
I think this is a conflict between different linked versions of LLVM in Terra and in the graphics driver (in particular the Mesa llvmpipe driver): see this issue in Julia https://github.com/JuliaLang/julia/issues/19606 . The reason it doesn't manifest when you export a binary from Terra is because the exported binary doesn't link llvm.

**Comment by elliottslaughter** [comment] 2018-09-20 23:40
If that's the issue, I would note that we've recently expanded our LLVM support to include 5 and 6, so there's a much better chance we can be on the same version of LLVM than in the past.

**Comment by OvermindDL1** [comment] 2018-09-21 14:50
As a point of data, my current mesa version uses LLVM 6.0.1.

**Comment by elliottslaughter** [comment] 2018-12-03 19:20
@max1220 can you confirm if moving to a more recent LLVM version fixes the problem? Thanks.

**Comment by elliottslaughter** [comment] 2019-08-19 23:51
Closing for now, but please feel free to contact us again if you have any further questions or issues.

**Closed by elliottslaughter** 2019-08-19 23:51 UTC
